import { useEffect, useMemo, useRef, useState } from 'react';
import type { Chart, ChartType } from 'chart.js';
import { buildChartConfig } from '../logic/chartOptions';
import type { IcrAnyChartModel } from '../types/charts';
import { ChartErrorState } from './ChartErrorState';
import { ChartTextSummary } from './ChartTextSummary';

type ChartAutoModule = typeof import('chart.js/auto');
type ChartConstructor = ChartAutoModule['default'];
type Loader = () => Promise<ChartAutoModule>;
const defaultLoader: Loader = () => import('chart.js/auto');
export function IcrChartCard({model,loadChart=defaultLoader}:{model:IcrAnyChartModel;loadChart?:Loader}){ const canvasRef=useRef<HTMLCanvasElement|null>(null); const chartRef=useRef<Chart<ChartType>|null>(null); const [status,setStatus]=useState<'idle'|'loading'|'ready'|'error'>(model.emptyReason?'idle':'loading'); const [error,setError]=useState<string|null>(null); const config=useMemo(()=>buildChartConfig(model),[model]); useEffect(()=>{ chartRef.current?.destroy(); chartRef.current=null; if(model.emptyReason){ setStatus('idle'); setError(null); return; } let cancelled=false; setStatus('loading'); setError(null); loadChart().then((mod)=>{ if(cancelled || !canvasRef.current) return; try { chartRef.current?.destroy(); const ChartCtor=mod.default as ChartConstructor; chartRef.current=new ChartCtor(canvasRef.current, config); setStatus('ready'); } catch(e) { setError(e instanceof Error?e.message:'Chart rendering failed.'); setStatus('error'); } }).catch((e:unknown)=>{ if(cancelled) return; setError(e instanceof Error?e.message:'Chart library failed to load.'); setStatus('error'); }); return ()=>{ cancelled=true; chartRef.current?.destroy(); chartRef.current=null; }; },[config,loadChart,model.emptyReason]); return <article className="icr-dashboard__chart-card" aria-labelledby={`${model.kind}-chart-title`}><div className="icr-dashboard__chart-heading"><h3 id={`${model.kind}-chart-title`}>{model.title}</h3><p>{model.description}</p></div><ChartTextSummary model={model} />{model.emptyReason?<ChartErrorState message={model.emptyReason} />:<div className="icr-dashboard__chart-frame" aria-describedby={`${model.kind}-chart-summary`} aria-busy={status==='loading'}>{status==='loading'?<p className="icr-dashboard__chart-loading">Loading chart…</p>:null}{status==='error'?<ChartErrorState message={error??'Chart rendering failed.'} />:null}<canvas ref={canvasRef} aria-label={`${model.title}. ${model.summary}`} role="img" hidden={status==='error'} /></div>}<p id={`${model.kind}-chart-summary`} className="icr-dashboard__sr-only">{model.summary}</p></article>; }
