import { buildHealthDistribution, buildRecommendationSummary } from './portfolioMetrics';
import { latestByClient } from './deepAnalytics';
import type { NormalisedRow } from '../types/icr';
import type { IcrChartModel, IcrChartPoint, IcrTrendChartModel, IcrTrendPoint } from '../types/charts';
const finite=(v:number|null|undefined): v is number=>Number.isFinite(v);
const monthLabel=(date:Date)=>new Intl.DateTimeFormat('en-GB',{month:'short',year:'numeric',timeZone:'UTC'}).format(date);
const monthKey=(date:Date)=>`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`;
const model=(kind:IcrChartModel['kind'],title:string,description:string,type:IcrChartModel['type'],points:IcrChartPoint[],empty:string):IcrChartModel=>({kind,title,description,type,points,labels:points.map((p)=>p.label),values:points.map((p)=>p.value),summary:points.length?points.map((p)=>`${p.label}: ${p.value}`).join(', '):empty,emptyReason:points.length&&points.some((p)=>p.value>0)?null:empty});
export function buildHealthChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const d=buildHealthDistribution(rows); return model('health','Health score distribution','Latest visible accounts grouped by calculated health score band.','doughnut',[{label:'Critical',value:d.Critical},{label:'Watch',value:d.Watch},{label:'Stable',value:d.Stable},{label:'Strong',value:d.Strong}],'No visible account health scores to chart.'); }
export function buildRagChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const counts=new Map<string,number>(); rows.forEach(r=>counts.set(r.rag,(counts.get(r.rag)??0)+1)); return model('rag','Account health/RAG mix','Manual RAG status for one latest row per visible client.','doughnut',[...counts].map(([label,value])=>({label,value})),'No visible RAG statuses to chart.'); }
export function buildUtilizationChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const points=rows.filter(r=>finite(r.leadUtil)).sort((a,b)=>(b.leadUtil??0)-(a.leadUtil??0)).slice(0,12).map(r=>({label:r.clientName||r._clientKey,value:Math.round((r.leadUtil??0)*100)})); return model('utilization','Lead capacity and utilisation','Latest captured leads as a share of subscribed capacity for priority accounts.','bar',points,'No lead utilisation values are available for the current filters.'); }
export function buildRiskChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const points=rows.filter(r=>finite(r.untouchedRate)||finite(r.unassignedRate)).map(r=>({label:r.clientName||r._clientKey,value:Math.round(((r.untouchedRate??0)+(r.unassignedRate??0))*50)})).sort((a,b)=>b.value-a.value).slice(0,12); return model('risk','Operational risk matrix','Composite of untouched and unassigned rates. Higher values need operational review.','bar',points,'No untouched or unassigned rates are available.'); }
export function buildBurdenChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const points=rows.map(r=>({label:r.clientName||r._clientKey,value:[r.unassigned,r.untouched,r.overdue,r.tickets].filter(finite).reduce((s,v)=>s+v,0)})).filter(p=>p.value>0).sort((a,b)=>b.value-a.value).slice(0,12); return model('burden','Operational burden by account','Latest unassigned, untouched, overdue and ticket counts combined by account.','bar',points,'No operational burden values are available.'); }
export function buildAdoptionChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const vals=[['Widget adoption','widgetAdoption'],['User adoption','userAdoption'],['Raw-data utilisation','rawAdoption']] as const; const points=vals.map(([label,key])=>{const xs=rows.map(r=>r[key]).filter(finite); return {label,value:xs.length?Math.round(xs.reduce((s,v)=>s+v,0)/xs.length*100):0};}); return model('adoption','Product adoption coverage','Average latest product adoption where source values are present.','bar',points,'No product adoption values are available.'); }
export function buildCommunicationChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const points=[['Email','emailConsumed'],['SMS','smsConsumed'],['WhatsApp','whatsappConsumed'],['NIAA','niaaConsumed']].map(([label,key])=>({label,value:rows.map(r=>r[key as 'emailConsumed'|'smsConsumed'|'whatsappConsumed'|'niaaConsumed']).filter(finite).reduce((s,v)=>s+v,0)})); return model('communication','Communication activity','Latest consumed communication credits and sessions across visible accounts.','bar',points,'No communication activity values are available.'); }
export function buildThemesChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const r=buildRecommendationSummary(rows); return model('themes','Recurring action themes','Most common deterministic recommendation themes in visible accounts.','bar',r.themes.map(t=>({label:t.label,value:t.count})),'No recurring recommendation themes are available.'); }
export function buildRecommendationChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const r=buildRecommendationSummary(rows); return model('recommendations','Recommendation actionability','Visible latest accounts grouped by whether the rule-based recommendation needs action.','bar',[{label:'Actionable',value:r.actionable},{label:'Informational',value:r.informational}],'No visible recommendations to chart.'); }
export function buildHealthTrendChartModel(rows: readonly NormalisedRow[]): IcrTrendChartModel { const buckets=new Map<string,{date:Date;sum:number;count:number}>(); rows.forEach((r)=>{ if(!r.timestamp || !finite(r.leads)) return; const key=monthKey(r.timestamp); const current=buckets.get(key)??{date:new Date(Date.UTC(r.timestamp.getUTCFullYear(),r.timestamp.getUTCMonth(),1)),sum:0,count:0}; current.sum+=r.leads; current.count+=1; buckets.set(key,current); }); const points:IcrTrendPoint[]=[...buckets.entries()].map(([dateKey,b])=>({dateKey,label:monthLabel(b.date),value:Math.round(b.sum),count:b.count})).sort((a,b)=>a.dateKey.localeCompare(b.dateKey)); const empty='At least two dated rows with lead values are needed for a trend chart.'; return {kind:'trend',title:'Lead volume trend over time',description:'Filtered historical rows grouped by calendar month; missing lead values are excluded.',type:'line',points,labels:points.map((p)=>p.label),values:points.map((p)=>p.value),summary:points.length>=2?points.map((p)=>`${p.label}: ${p.value} leads from ${p.count} row${p.count===1?'':'s'}`).join(', '):empty,emptyReason:points.length>=2?null:empty}; }
export function buildExecutiveChartModels(latestRows: readonly NormalisedRow[], historicalRows: readonly NormalisedRow[]) { const latest=latestByClient(latestRows); return [buildUtilizationChartModel(latest),buildRagChartModel(latest),buildHealthTrendChartModel(historicalRows),buildRiskChartModel(latest),buildBurdenChartModel(latest),buildAdoptionChartModel(latest),buildCommunicationChartModel(latest),buildHealthChartModel(latest),buildThemesChartModel(latest)]; }
export function buildOwnerChartModel(rows: readonly NormalisedRow[], limit=8): IcrChartModel { const counts=new Map<string,number>(); rows.forEach((r)=>{ if(r.owner) counts.set(r.owner,(counts.get(r.owner)??0)+1); }); const points=[...counts.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value||a.label.localeCompare(b.label)).slice(0,limit); return model('owners','Owner portfolio distribution','Visible latest client snapshots with a non-empty owner, sorted by account count.','bar',points,'No owner values are available for the current filters.'); }
