import { buildHealthDistribution, buildRecommendationSummary } from './portfolioMetrics';
import type { NormalisedRow } from '../types/icr';
import type { IcrChartModel, IcrChartPoint, IcrTrendChartModel, IcrTrendPoint } from '../types/charts';
const finite=(v:number|null|undefined): v is number=>Number.isFinite(v);
const monthLabel=(date:Date)=>new Intl.DateTimeFormat('en-GB',{month:'short',year:'numeric',timeZone:'UTC'}).format(date);
const monthKey=(date:Date)=>`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`;
const model=(kind:IcrChartModel['kind'],title:string,description:string,type:IcrChartModel['type'],points:IcrChartPoint[],empty:string):IcrChartModel=>({kind,title,description,type,points,labels:points.map((p)=>p.label),values:points.map((p)=>p.value),summary:points.length?points.map((p)=>`${p.label}: ${p.value}`).join(', '):empty,emptyReason:points.length&&points.some((p)=>p.value>0)?null:empty});
export function buildHealthChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const d=buildHealthDistribution(rows); const points=[{label:'Critical',value:d.Critical},{label:'Watch',value:d.Watch},{label:'Stable',value:d.Stable},{label:'Strong',value:d.Strong}]; return model('health','Health distribution','Current latest visible client snapshots grouped by prototype health score bands.','doughnut',points,'No visible account health scores to chart.'); }
export function buildRecommendationChartModel(rows: readonly NormalisedRow[]): IcrChartModel { const r=buildRecommendationSummary(rows); const points=[{label:'Actionable',value:r.actionable},{label:'Informational',value:r.informational}]; return model('recommendations','Recommendation distribution','Current latest visible client snapshots grouped by existing Phase 3A actionability semantics.','bar',points,'No visible recommendations to chart.'); }
export function buildOwnerChartModel(rows: readonly NormalisedRow[], limit=8): IcrChartModel { const counts=new Map<string,number>(); rows.forEach((r)=>{ if(r.owner) counts.set(r.owner,(counts.get(r.owner)??0)+1); }); const points=[...counts.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value||a.label.localeCompare(b.label)).slice(0,limit); return model('owners','Owner portfolio distribution','Visible latest client snapshots with a non-empty owner, sorted by account count.','bar',points,'No owner values are available for the current filters.'); }
export function buildHealthTrendChartModel(rows: readonly NormalisedRow[]): IcrTrendChartModel { const buckets=new Map<string,{date:Date;sum:number;count:number}>(); rows.forEach((r)=>{ if(!r.timestamp || !finite(r.health)) return; const key=monthKey(r.timestamp); const current=buckets.get(key)??{date:new Date(Date.UTC(r.timestamp.getUTCFullYear(),r.timestamp.getUTCMonth(),1)),sum:0,count:0}; current.sum+=r.health; current.count+=1; buckets.set(key,current); }); const points:IcrTrendPoint[]=[...buckets.entries()].map(([dateKey,b])=>({dateKey,label:monthLabel(b.date),value:Math.round(b.sum/b.count),count:b.count})).sort((a,b)=>a.dateKey.localeCompare(b.dateKey)); const empty='At least two dated rows with finite health scores are needed for a trend chart.'; return {kind:'trend',title:'Average health trend',description:'Historical parsed rows grouped by calendar month; duplicate-month rows are averaged without interpolation.',type:'line',points,labels:points.map((p)=>p.label),values:points.map((p)=>p.value),summary:points.length>=2?points.map((p)=>`${p.label}: ${p.value} avg health from ${p.count} row${p.count===1?'':'s'}`).join(', '):empty,emptyReason:points.length>=2?null:empty}; }
export function buildExecutiveChartModels(latestRows: readonly NormalisedRow[], historicalRows: readonly NormalisedRow[]) { return [buildHealthChartModel(latestRows),buildRecommendationChartModel(latestRows),buildOwnerChartModel(latestRows),buildHealthTrendChartModel(historicalRows)]; }
