import { buildAccountPriorityRows } from './accountPriority';
import { buildHealthTrendChartModel } from './chartSelectors';
import { healthCategory } from './healthScore';
import { dateKey } from './parseDate';
import type { NormalisedRow, RagStatus } from '../types/icr';
import type { IcrTrendChartModel } from '../types/charts';
export interface ClientFilters { search?: string; owner?: string; rag?: RagStatus; status?: string }
export interface ClientSummary { clientKey:string; clientName:string; clientId:string; latest:NormalisedRow; rows:NormalisedRow[]; snapshotCount:number; earliestDate:Date|null; latestDate:Date|null; owner:string; rag:RagStatus; status:string; health:number; category:ReturnType<typeof healthCategory>; recommendation:string; tickets:number|null; priorityRank:number }
const byLatest=(rows: readonly NormalisedRow[])=>[...rows].sort((a,b)=>dateKey(b.timestamp)-dateKey(a.timestamp)||a._row-b._row);
export function sortClientHistory(rows: readonly NormalisedRow[]): NormalisedRow[] { return [...rows].sort((a,b)=>dateKey(b.timestamp)-dateKey(a.timestamp)||a._row-b._row); }
export function buildClientSummaries(rows: readonly NormalisedRow[]): ClientSummary[] { const groups=new Map<string,NormalisedRow[]>(); rows.forEach((r)=>{ if(r._clientKey) groups.set(r._clientKey,[...(groups.get(r._clientKey)??[]),r]); }); const priority=new Map(buildAccountPriorityRows(rows).map((r)=>[r.clientKey,r.priorityRank])); return [...groups.entries()].map(([clientKey,group])=>{ const sorted=byLatest(group); const latest=sorted[0]; const dates=group.map((r)=>r.timestamp).filter((d):d is Date=>Boolean(d)).sort((a,b)=>a.getTime()-b.getTime()); return {clientKey,clientName:latest.clientName || clientKey,clientId:latest.clientId,latest,rows:sortClientHistory(group),snapshotCount:group.length,earliestDate:dates[0]??null,latestDate:dates[dates.length-1]??null,owner:latest.owner,rag:latest.rag,status:latest.trackingStatus||latest.flowStatus,health:latest.health,category:healthCategory(latest.health),recommendation:latest.recommendation,tickets:latest.tickets,priorityRank:priority.get(clientKey)??999999}; }).sort((a,b)=>a.priorityRank-b.priorityRank||a.clientName.localeCompare(b.clientName)||a.clientKey.localeCompare(b.clientKey)); }
export function deriveClientFilterOptions(clients: readonly ClientSummary[]) { return {owners:[...new Set(clients.map((c)=>c.owner).filter(Boolean))].sort(), rags:[...new Set(clients.map((c)=>c.rag))].sort(), statuses:[...new Set(clients.map((c)=>c.status).filter(Boolean))].sort()}; }
export function filterClientSummaries(clients: readonly ClientSummary[], filters: ClientFilters): ClientSummary[] { const q=filters.search?.trim().toLowerCase(); return clients.filter((c)=>(!filters.owner||c.owner===filters.owner)&&(!filters.rag||c.rag===filters.rag)&&(!filters.status||c.status===filters.status)&&(!q||[c.clientName,c.clientId,c.owner,c.status,c.recommendation].some((v)=>v.toLowerCase().includes(q)))); }
export function chooseSelectedClientKey(clients: readonly ClientSummary[], current?: string | null): string | null { return clients.some((c)=>c.clientKey===current) ? current as string : clients[0]?.clientKey ?? null; }
export function buildClientTrend(summary: ClientSummary | null): IcrTrendChartModel | null { return summary ? {...buildHealthTrendChartModel(summary.rows),title:'Selected client health trend',description:'Selected client historical rows grouped by month; duplicate-month health scores are averaged.'} : null; }
export function activeClientFilterCount(filters: ClientFilters): number { return [filters.search?.trim(),filters.owner,filters.rag,filters.status].filter(Boolean).length; }
