import { FIELD_DEFS, REQUIRED_FIELD_KEYS } from '../constants/fields';
import { summariseDataQuality } from './dataQuality';
import type { CanonicalFieldKey, DataQualityIssue, NormalisedRow } from '../types/icr';
import type { HeaderMapping } from '../types/mapping';
import type { ColumnMappingState } from '../types/upload';
const isPopulated=(value:unknown): boolean=>{ if(value===null||value===undefined) return false; if(typeof value==='string') return value.trim().length>0; if(typeof value==='number') return Number.isFinite(value); return true; };
const pct=(a:number,b:number)=>b?Math.round((a/b)*100):null;
export function buildIssueGroups(issues: readonly DataQualityIssue[]) { const map=new Map<string,{type:string;count:number;rows:Set<number>;issue:string;resolution:string}>(); issues.forEach((i)=>{ const g=map.get(i.type)??{type:i.type,count:0,rows:new Set<number>(),issue:i.issue,resolution:i.resolution}; g.count+=1; if(typeof i.row==='number') g.rows.add(i.row); if(!g.issue&&i.issue) g.issue=i.issue; if(!g.resolution&&i.resolution) g.resolution=i.resolution; map.set(i.type,g); }); return [...map.values()].map((g)=>({type:g.type,label:g.type.split('-').map((p)=>p[0]?.toUpperCase()+p.slice(1)).join(' '),count:g.count,affectedRows:g.rows.size,issue:g.issue,resolution:g.resolution})).sort((a,b)=>b.count-a.count||a.type.localeCompare(b.type)); }
export function buildFieldCompleteness(rows: readonly NormalisedRow[], mapping: HeaderMapping | ColumnMappingState | null | undefined) { return [...FIELD_DEFS].sort((a,b)=>Number(b.required)-Number(a.required)||FIELD_DEFS.indexOf(a)-FIELD_DEFS.indexOf(b)).map((field)=>{ const populated=rows.filter((row)=>isPopulated(row[field.key as keyof NormalisedRow])).length; const missing=rows.length-populated; const mapped=Boolean(mapping&&Object.entries(mapping).some(([key,value])=>typeof value==='string'?key===field.key:value?.key===field.key)); return {key:field.key,label:field.label,required:field.required,populated,missing,percent:pct(populated,rows.length),mapped}; }); }
export function buildMappingCoverage(mapping: HeaderMapping | ColumnMappingState | null | undefined) { return FIELD_DEFS.map((field)=>{ const entry=mapping?Object.entries(mapping).find(([key,value])=>typeof value==='string'?key===field.key:value?.key===field.key):undefined; const value=entry?.[1]; const sourceHeader=typeof value==='string'?value:value?.sourceHeader??''; const status=typeof value==='string'?'mapped':value?.status??'unmapped'; const score=typeof value==='string'?undefined:value?.score; return {key:field.key,label:field.label,required:field.required,sourceHeader,status,score}; }); }
export function buildQualityOverview(rows: readonly NormalisedRow[], issues: readonly DataQualityIssue[], mappedColumnCount:number, skippedRows:number, mapping:HeaderMapping|ColumnMappingState|null|undefined) { const summary=summariseDataQuality(rows,issues,mappedColumnCount); const affectedRows=new Set(issues.map((i)=>i.row).filter((r):r is number=>typeof r==='number')).size; const mappedKeys=new Set(mapping?Object.entries(mapping).map(([key,value])=>typeof value==='string'?key:value.key).filter(Boolean) as CanonicalFieldKey[]:[]); const requiredMapped=REQUIRED_FIELD_KEYS.filter((k)=>mappedKeys.has(k)).length; const optional=FIELD_DEFS.filter((f)=>!f.required); const optionalMapped=optional.filter((f)=>mappedKeys.has(f.key)).length; return {quality:summary.quality,rowCount:rows.length,skippedRows,issueCount:issues.length,affectedRows,mappedFieldCount:mappedColumnCount,requiredCoverage:{mapped:requiredMapped,total:REQUIRED_FIELD_KEYS.length,percent:pct(requiredMapped,REQUIRED_FIELD_KEYS.length)},optionalCoverage:{mapped:optionalMapped,total:optional.length,percent:pct(optionalMapped,optional.length)}}; }
export function issueExamples(issues: readonly DataQualityIssue[], limit=25) { return issues.slice(0,limit); }
export { isPopulated as isFieldValuePopulated };
