import { dateKey } from './parseDate';
import type { NormalisedRow } from '../types/icr';
const finite=(v:unknown): v is number=>typeof v==='number'&&Number.isFinite(v);
type Insight={sev:number;title:string;client:string;why:string;action:string;evidence:string};
type MetricKey=typeof metricSpecs[number][1];
type MetricRow={group:string;key:string;label:string;format:string;direction:string;latest:number;previous:number|null;average:number;median:number;min:number;max:number;change:number;latestChange:number|null;volatility:number;trend:string;coverage:number;values:number[];interpretation:string};
type FieldInfo={source:string;type:string;latest:string;previous:string;coverage:number;history:string[];meaning:string;interpretation:string};
type Diagnostic=[string,string];
const valueFor=(row: NormalisedRow, key: string): unknown => (row as unknown as Record<string, unknown>)[key];
const avg=(a:number[])=>a.reduce((s,v)=>s+v,0)/a.length;
const median=(a:number[])=>{const s=[...a].sort((x,y)=>x-y); const m=Math.floor(s.length/2); return s.length%2?s[m]:(s[m-1]+s[m])/2};
export const pct=(v:number|null|undefined)=>finite(v)?`${Math.round(v*100)}%`:'—';
export const num=(v:number|null|undefined)=>finite(v)?new Intl.NumberFormat('en-GB').format(v):'—';
export const fmtDate=(d:Date|null|undefined)=>d?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(d):'—';
export const latestByClient=(rows:readonly NormalisedRow[])=>{const m=new Map<string,NormalisedRow>(); rows.forEach(r=>{const old=m.get(r._clientKey); if(!old||dateKey(r.timestamp)>dateKey(old.timestamp)||dateKey(r.timestamp)===dateKey(old.timestamp)&&r._row>old._row)m.set(r._clientKey,r)}); return [...m.values()]};
export function portfolioHero(rows:readonly NormalisedRow[], issues:number){const latest=latestByClient(rows); const hs=latest.map(r=>r.health).filter(finite); const score=hs.length?Math.round(avg(hs)):null; const risk=latest.find(r=>(r.untouchedRate??0)>=.35)||latest.find(r=>(r.unassignedRate??0)>=.2)||latest.find(r=>r.health<50); const opp=latest.find(r=>r.opportunity)||latest.find(r=>(r.leadUtil??0)>1); return {score,condition:score===null?'Not enough scored account data':score<50?'Portfolio needs immediate recovery focus':score<70?'Portfolio is mixed with visible execution risk':score<85?'Portfolio is broadly stable with targeted gaps':'Portfolio is healthy and expansion-ready',primaryRisk:risk?`${risk.clientName}: ${risk.untouchedRate!==null?`${pct(risk.untouchedRate)} untouched leads`:risk.unassignedRate!==null?`${pct(risk.unassignedRate)} unassigned leads`:`health ${risk.health}`}`:'No material risk surfaced in visible accounts',primaryOpportunity:opp?`${opp.clientName}: ${opp.opportunity||'validate capacity and renewal scope'}`:'No explicit opportunity recorded in visible accounts',confidence:issues?`${issues} data issue${issues===1?'':'s'} to review`:'Workbook parsed with no recorded issues',activeAccounts:latest.length};}
export function executiveKpis(rows:readonly NormalisedRow[]){const latest=latestByClient(rows); const medianUtil=median(latest.map(r=>r.leadUtil).filter(finite)); const high=latest.filter(r=>r.health<70||r.rag==='Red'||r.rag==='Amber').length; const untouched=latest.map(r=>r.untouched).filter(finite).reduce((s,v)=>s+v,0); const overdue=latest.map(r=>r.overdue).filter(finite).reduce((s,v)=>s+v,0); const dtc=latest.filter(r=>r.dtcPlaced===true).length; return [
{label:'Active accounts',value:String(latest.length),help:'One latest snapshot per client in the current filter.',tone:'primary'},
{label:'Median lead utilisation',value:Number.isFinite(medianUtil)?pct(medianUtil):'—',help:'Middle account utilisation; missing capacity values stay excluded.',tone:'secondary'},
{label:'High-priority accounts',value:String(high),help:'Accounts with weak calculated health or red/amber manual RAG.',tone:high?'critical':'positive'},
{label:'Untouched leads',value:num(untouched),help:'Latest untouched backlog across visible accounts.',tone:untouched?'warning':'positive'},
{label:'Overdue follow-ups',value:num(overdue),help:'Latest overdue follow-up workload across visible accounts.',tone:overdue?'warning':'positive'},
{label:'Tracking/DTC coverage',value:latest.length?`${Math.round(dtc/latest.length*100)}%`:'—',help:'Accounts explicitly reporting tracking placement.',tone:dtc===latest.length?'positive':'warning'}] as const;}
export function attentionInsights(rows:readonly NormalisedRow[]){const latest=latestByClient(rows); const items=latest.flatMap(r=>{const out: Insight[]=[]; if((r.untouchedRate??0)>=.35)out.push({sev:3,title:'Untouched lead backlog is high',client:r.clientName,why:'First-contact execution may be limiting conversion.',action:'Run an owner-led untouched-lead recovery sprint.',evidence:`${pct(r.untouchedRate)} untouched (${num(r.untouched)} leads)`}); if((r.unassignedRate??0)>=.2)out.push({sev:3,title:'Lead allocation needs attention',client:r.clientName,why:'Unassigned leads can hide demand and delay follow-up.',action:'Inspect allocation rules and clear the backlog.',evidence:`${pct(r.unassignedRate)} unassigned (${num(r.unassigned)} leads)`}); if(r.leadUtil!==null&&r.leadUtil>1)out.push({sev:2,title:'Leads exceed subscribed capacity',client:r.clientName,why:'Commercial entitlement or capacity handling should be validated.',action:'Confirm subscription capacity and expansion scope.',evidence:`${pct(r.leadUtil)} utilisation`}); if(r.dtcPlaced===false&&(r.leads??0)>0)out.push({sev:2,title:'Tracking gap with active lead volume',client:r.clientName,why:'Attribution reporting may be unreliable until tracking is complete.',action:'Complete DTC/tracking implementation and re-check source reporting.',evidence:`${num(r.leads)} leads while tracking is not placed`}); if(r.opportunity)out.push({sev:1,title:'Commercial opportunity recorded',client:r.clientName,why:'The workbook contains an explicit business opportunity.',action:'Qualify owner, value, next step, and target date.',evidence:r.opportunity}); return out;}); return items.sort((a,b)=>b.sev-a.sev||a.client.localeCompare(b.client)).slice(0,5);}
export const metricSpecs=[['Account health','health','Calculated health','score','higher'],['Lead capacity','leads','Leads captured','number','neutral'],['Lead capacity','subscribedLeads','Leads subscribed','number','neutral'],['Lead capacity','leadUtil','Lead utilisation','percent','target'],['Lead operations','unassigned','Unassigned leads','number','lower'],['Lead operations','unassignedRate','Unassigned lead rate','percent','lower'],['Lead operations','untouched','Untouched leads','number','lower'],['Lead operations','untouchedRate','Untouched lead rate','percent','lower'],['Lead operations','overdue','Overdue follow-ups','number','lower'],['Product adoption','widgetAdoption','Widget adoption','percent','higher'],['Product adoption','userAdoption','User adoption','percent','higher'],['Product adoption','rawAdoption','Raw-data utilisation','percent','higher'],['Communication','emailConsumed','Email credits consumed','number','neutral'],['Communication','smsConsumed','SMS credits consumed','number','neutral'],['Communication','whatsappConsumed','WhatsApp credits consumed','number','neutral'],['Communication','niaaConsumed','NIAA sessions consumed','number','neutral'],['Queries and support','tickets','Zendesk tickets','number','lower']] as const;
export function metricRows(rows:readonly NormalisedRow[]): MetricRow[]{const asc=[...rows].sort((a,b)=>dateKey(a.timestamp)-dateKey(b.timestamp)||a._row-b._row); return metricSpecs.map(([group,key,label,format,direction])=>{const vals=asc.map(r=>valueFor(r,key as MetricKey)).filter(finite); if(!vals.length)return null; const latest=vals[vals.length-1]!; const previous=vals.length>1?vals[vals.length-2]!:null; const change=latest-vals[0]; const latestChange=previous===null?null:latest-previous; const av=avg(vals); const vol=vals.length>1?Math.sqrt(avg(vals.map(v=>(v-av)**2))):0; const trend=vals.length<2?'Not enough history':Math.abs(change)<1e-9?'Flat':change>0?'Increasing':'Decreasing'; return {group,key,label,format,direction,latest,previous,average:av,median:median(vals),min:Math.min(...vals),max:Math.max(...vals),change,latestChange,volatility:vol,trend,coverage:vals.length/asc.length,values:vals,interpretation:vals.length<2?'Only one valid observation is available.':`${label} is ${trend.toLowerCase()} over the observed period; coverage is ${Math.round(vals.length/asc.length*100)}%.`};}).filter((row)=>row!==null) as MetricRow[];}
export function statusHistory(rows:readonly NormalisedRow[]){const asc=[...rows].sort((a,b)=>dateKey(a.timestamp)-dateKey(b.timestamp)||a._row-b._row); const fields=[['RAG transitions','rag'],['Tracking implementation','trackingStatus'],['Applicant flow','flowStatus'],['CS ownership','owner'],['Key actionables','actionable'],['Business opportunities','opportunity'],['Latest meeting','lastMeeting'],['Training/workshop','lastTraining'],['Report presentation','lastReport'],['QBR','lastQbr']] as const; return fields.map(([label,key])=>{const vals=asc.map(r=>valueFor(r,key)).filter(Boolean); const seq=vals.filter((v,i)=>i===0||String(v)!==String(vals[i-1])); return {label,latest:vals[vals.length-1]??'',changes:Math.max(0,seq.length-1),history:seq.slice(-6).map(v=>v instanceof Date?fmtDate(v):String(v)),freshness:vals[vals.length-1] instanceof Date&&asc[asc.length-1]?.timestamp?`${Math.round((asc[asc.length-1]!.timestamp!.getTime()-(vals[vals.length-1] as Date).getTime())/86400000)} days before latest review`:''};}).filter(x=>x.latest||x.history.length);}
export function fieldRegister(rows:readonly NormalisedRow[]): FieldInfo[]{const asc=[...rows].sort((a,b)=>dateKey(a.timestamp)-dateKey(b.timestamp)||a._row-b._row); const headers=[...new Set(asc.flatMap(r=>Object.keys(r._raw)))]; return headers.map(h=>{const vals=asc.map(r=>r._raw[h]).filter(v=>v!==null&&v!==undefined&&String(v).trim()!==''); if(!vals.length)return null; return {source:h,type:/date|time/i.test(h)?'date':vals.some(v=>Number.isFinite(Number(String(v).replace(/[,/%]/g,''))))?'number/text':'text',latest:String(vals[vals.length-1]),previous:vals.length>1?String(vals[vals.length-2]):'',coverage:vals.length/asc.length,history:vals.slice(-5).map(String),meaning:'Uploaded field preserved as source evidence',interpretation:`${vals.length} of ${asc.length} snapshots contain this field; ${vals.length>1?'recent values are shown for review.':'only one value is available.'}`};}).filter((row): row is FieldInfo=>Boolean(row));}
export function advancedDiagnostics(rows:readonly NormalisedRow[]): Diagnostic[]{const sorted=[...rows].sort((a,b)=>dateKey(a.timestamp)-dateKey(b.timestamp)||a._row-b._row); const latest=sorted[sorted.length-1]; if(!latest)return []; const out: Diagnostic[]=[]; const manual: Record<string, number>={Green:85,Amber:60,Red:35,Purple:55,Unknown:50}; const manualScore=manual[latest.rag]??50; if(Math.abs(latest.health-manualScore)>=20)out.push(['Manual RAG mismatch',`Manual RAG is ${latest.rag}; calculated health is ${latest.health}. Review the difference explicitly.`]); if((latest.untouchedRate??0)>.25&&(latest.userAdoption??1)<.75)out.push(['Untouched leads with low user adoption',`${pct(latest.untouchedRate)} untouched and ${pct(latest.userAdoption)} user adoption are both present.`]); if((latest.unassignedRate??0)>.2&&/allocation|manual|offline|source|rule|automation/i.test(String(valueFor(latest,'unassignedReason')||'')))out.push(['Allocation issue has text evidence',`Reason text supports the numerical allocation gap.`]); if((latest.leadUtil??0)>1)out.push(['Lead utilisation above capacity',`${pct(latest.leadUtil)} utilisation exceeds subscribed capacity.`]); if(latest.dtcPlaced===false&&(latest.leads??0)>0)out.push(['Tracking gap despite lead volume',`${num(latest.leads)} leads are present while tracking is not placed.`]); return out;}
