import { buildAccountPriorityRows } from './accountPriority';
import { buildHealthChartModel, buildRecommendationChartModel } from './chartSelectors';
import { buildClientTrend, type ClientSummary } from './clientIntelligence';
import { buildFieldCompleteness, buildIssueGroups, buildMappingCoverage, buildQualityOverview } from './dataQualityMetrics';
import { healthCategory } from './healthScore';
import { buildPortfolioSummary } from './portfolioMetrics';
import type { ExportTable } from './csvExport';
import type { NormalisedRow, DataQualityIssue } from '../types/icr';
import type { ColumnMappingState } from '../types/upload';
import type { ReportFilterState } from '../types/report';
const d=(date:Date|null)=>date?date.toISOString().slice(0,10):'';
export interface WorkbookModel { sheets: ExportTable[] }
export function executiveTables(rows: readonly NormalisedRow[], issues: readonly DataQualityIssue[], filters: ReportFilterState): WorkbookModel { const priority=buildAccountPriorityRows(rows); const summary=buildPortfolioSummary(rows,issues); const health=buildHealthChartModel(rows); const rec=buildRecommendationChartModel(rows); return {sheets:[{name:'Executive Summary',headers:['Metric','Value'],rows:[['Accounts',summary.accountCount],['Snapshots',summary.snapshotCount],['Average Health',summary.averageHealth??''],['Accounts Needing Action',summary.accountsNeedingAction],['Active Filters',Object.entries(filters).filter(([,v])=>Boolean(v)).map(([k])=>k).join(', ')||'None'],['Local Processing','Generated in browser only']]},{name:'Accounts',headers:['Client Name','Client ID','Owner','RAG','Status','Snapshot Date','Health Score','Health Category','Recommendation','Ticket Count'],rows:priority.map((r)=>[r.clientName,r.row.clientId,r.owner,r.rag,r.status,d(r.timestamp),r.health,r.category,r.recommendation,r.tickets??''])},{name:'Health Distribution',headers:['Category','Count'],rows:health.points.map((p)=>[p.label,p.value])},{name:'Recommendations',headers:['Category','Count'],rows:rec.points.map((p)=>[p.label,p.value])},{name:'Export Metadata',headers:['Field','Value'],rows:[['Exported View','Executive Report'],['Exported At',new Date().toISOString()],['Visible Account Count',rows.length]]}]}; }
export function clientTables(client: ClientSummary): WorkbookModel { const trend=buildClientTrend(client); return {sheets:[{name:'Client Summary',headers:['Field','Value'],rows:[['Client Name',client.clientName],['Client ID',client.clientId],['Owner',client.owner],['RAG',client.rag],['Status',client.status],['Latest Date',d(client.latestDate)],['Health Score',client.health],['Health Category',client.category],['Recommendation',client.recommendation],['Snapshots',client.snapshotCount]]},{name:'Client History',headers:['Date','Health Score','Health Category','RAG','Status','Owner','Tickets','Lead Utilisation','Recommendation'],rows:client.rows.map((r)=>[d(r.timestamp),r.health,healthCategory(r.health),r.rag,r.trackingStatus||r.flowStatus,r.owner,r.tickets??'',r.leadUtil??'',r.recommendation])},{name:'Health Trend',headers:['Month','Average Health','Source Rows'],rows:trend?.points.map((p)=>[p.label,p.value,p.count])??[]},{name:'Export Metadata',headers:['Field','Value'],rows:[['Exported View','Client Intelligence'],['Client',client.clientName],['Exported At',new Date().toISOString()],['Local Processing','Generated in browser only']]}]}; }
export function qualityTables(rows: readonly NormalisedRow[], issues: readonly DataQualityIssue[], mappedColumnCount:number, skippedRows:number, mapping:ColumnMappingState): WorkbookModel { const overview=buildQualityOverview(rows,issues,mappedColumnCount,skippedRows,mapping); const groups=buildIssueGroups(issues); const fields=buildFieldCompleteness(rows,mapping); const coverage=buildMappingCoverage(mapping); return {sheets:[{name:'Quality Overview',headers:['Metric','Value'],rows:[['Quality Score',overview.quality],['Parsed Rows',overview.rowCount],['Skipped Rows',overview.skippedRows],['Issues',overview.issueCount],['Affected Rows',overview.affectedRows],['Mapped Fields',overview.mappedFieldCount]]},{name:'Issue Breakdown',headers:['Type','Label','Count','Affected Rows','Issue','Resolution'],rows:groups.map((g)=>[g.type,g.label,g.count,g.affectedRows,g.issue,g.resolution])},{name:'Field Completeness',headers:['Field','Required','Mapped','Populated','Missing','Completeness Percent'],rows:fields.map((f)=>[f.label,f.required,f.mapped,f.populated,f.missing,f.percent??''])},{name:'Mapping Coverage',headers:['Field','Required','Source Column','Status','Confidence'],rows:coverage.map((m)=>[m.label,m.required,m.sourceHeader,m.status,m.score??''])},{name:'Issue Examples',headers:['Type','Row','Field','Issue','Resolution'],rows:issues.slice(0,1000).map((i)=>[i.type,i.row??'',i.field??'',i.issue,i.resolution])},{name:'Export Metadata',headers:['Field','Value'],rows:[['Exported View','Data Quality'],['Exported At',new Date().toISOString()],['Local Processing','Generated in browser only']]}]}; }
export const firstTableCsv=(model:WorkbookModel, preferred:string)=>model.sheets.find((s)=>s.name===preferred)??model.sheets[0];
