import { FIELD_BY_KEY } from '../constants/fields';
import type { CanonicalFieldKey, DataQualityIssue, NormalisedRow, PairValue, RagStatus, RawRow } from '../types/icr';
import type { HeaderMapping } from '../types/mapping';
import { healthScore } from './healthScore';
import { isMissing, normaliseHeader, safeString } from './normaliseHeader';
import { parseDate } from './parseDate';
import { parseNumber } from './parseNumber';
import { pairRatio, parsePair } from './parsePair';
import { recommendation } from './recommendations';
export function normalizeRag(value: unknown): RagStatus { const s=normaliseHeader(value); if(s.includes('red')) return 'Red'; if(s.includes('amber')||s.includes('yellow')) return 'Amber'; if(s.includes('purple')) return 'Purple'; if(s.includes('green')) return 'Green'; return 'Unknown'; }
export function canonicalClient(row: Pick<NormalisedRow,'clientId'|'clientName'>): string { const id=safeString(row.clientId); if(id&&/^\d+$/.test(id)) return `id:${id}`; return `name:${normaliseHeader(row.clientName).replace(/private limited|opc|college of technical education|education private limited/g,'').trim()}`; }
function ratio(a:number|null,b:number|null){return Number.isFinite(a)&&Number.isFinite(b)&&b!==0?(a as number)/(b as number):null}
export function normaliseRow(src: RawRow, mapping: HeaderMapping, rowNumber=2): { row: NormalisedRow | null; issues: DataQualityIssue[] } { const issues:DataQualityIssue[]=[]; const byKey=new Map<CanonicalFieldKey, unknown>(); for(const [header,m] of Object.entries(mapping)){ if(m.key && m.status!=='duplicate' && m.status!=='ambiguous') byKey.set(m.key, src[header]); }
 const pair=(k:CanonicalFieldKey):PairValue|null=>{const raw=byKey.get(k); const r=parsePair(raw); if(!r.ok&&!isMissing(raw)) issues.push({type:'invalid-pair',row:rowNumber,field:k,rawValue:raw,issue:'No numeric value found',resolution:'Stored as missing'}); if(r.ok&&r.diagnostics.length) issues.push({type:'ambiguous-pair',row:rowNumber,field:k,rawValue:raw,issue:'Ambiguous numeric format',resolution:'First two detected values used with caution'}); return r.ok?r.value:null};
 const num=(k:CanonicalFieldKey):number|null=>{const raw=byKey.get(k); const r=parseNumber(raw); if(!r.ok&&!isMissing(raw)) issues.push({type:'invalid-number',row:rowNumber,field:k,rawValue:raw,issue:'No numeric value found',resolution:'Stored as missing'}); return r.ok?r.value:null};
 const dateRaw=byKey.get('timestamp'); const date=parseDate(dateRaw); if(!date.ok&&!isMissing(dateRaw)) issues.push({type:'invalid-date',row:rowNumber,field:'timestamp',rawValue:dateRaw,issue:'Unrecognised date',resolution:'Excluded from date calculations'});
 for(const def of Object.values(FIELD_BY_KEY)) if(def.required && isMissing(byKey.get(def.key))) issues.push({type:'missing-required-field',row:rowNumber,field:def.key,rawValue:byKey.get(def.key),issue:'Required field is missing',resolution:'Row retained with fallback where possible'});
 const leadPair=pair('leadPair'), unassignedPair=pair('unassignedPair'), widgetPair=pair('widgetPair'), userPair=pair('userPair'), rawPair=pair('rawPair'); const tickets=num('tickets'); const clientName=safeString(byKey.get('clientName')) || `Unknown client ${Math.max(1,rowNumber-1)}`; const clientId=safeString(byKey.get('clientId')); const rowBase={_row:rowNumber,_raw:src,_warnings:issues,_custom:{},timestamp:date.ok?date.value:null,clientName,clientId,rag:normalizeRag(byKey.get('rag')),owner:safeString(byKey.get('owner')),manager:safeString(byKey.get('manager')),trackingStatus:safeString(byKey.get('trackingStatus')),flowStatus:safeString(byKey.get('flowStatus')),opportunity:safeString(byKey.get('opportunity')),actionable:safeString(byKey.get('actionable')),leadPair,unassignedPair,paidPair:pair('paidPair'),widgetPair,userPair,rawPair,queryPair:pair('queryPair'),emailPair:pair('emailPair'),smsPair:pair('smsPair'),whatsappPair:pair('whatsappPair'),niaaPair:pair('niaaPair'),leads:leadPair?.a??null,subscribedLeads:leadPair?.b??null,unassigned:unassignedPair?.a??null,untouched:num('untouched'),overdue:num('overdue'),activeWidgets:widgetPair?.a??null,subscribedWidgets:widgetPair?.b??null,activeUsers:userPair?.a??null,subscribedUsers:userPair?.b??null,activeRaw:rawPair?.a??null,subscribedRaw:rawPair?.b??null,tickets,emailConsumed:null,smsConsumed:null,whatsappConsumed:null,niaaConsumed:null,leadUtil:pairRatio(leadPair),unassignedRate:null,untouchedRate:null,overdueRate:null,widgetAdoption:pairRatio(widgetPair),userAdoption:pairRatio(userPair),rawAdoption:pairRatio(rawPair),dtcPlaced:null,health:0,recommendation:''} as Omit<NormalisedRow, '_clientKey'>;
 const withRatios={...rowBase,_clientKey:canonicalClient(rowBase),unassignedRate:ratio(rowBase.unassigned,rowBase.leads),untouchedRate:ratio(rowBase.untouched,rowBase.leads),overdueRate:ratio(rowBase.overdue,rowBase.leads),dtcPlaced: rowBase.trackingStatus ? (/placed/i.test(rowBase.trackingStatus)&&!/not placed|missing|need correction/i.test(rowBase.trackingStatus)) : null}; const finalRow={...withRatios,health:healthScore(withRatios)}; return {row:{...finalRow,recommendation:recommendation(finalRow)},issues}; }
export function normaliseRows(rows: readonly RawRow[], mapping: HeaderMapping): { rows: NormalisedRow[]; issues: DataQualityIssue[] } { const out=rows.map((r,i)=>normaliseRow(r,mapping,i+2)); return {rows:out.flatMap((x)=>x.row?[x.row]:[]),issues:out.flatMap((x)=>x.issues)}; }
