import { healthCategory } from './healthScore';
import { isActionableRecommendation } from './reportSelectors';
import type { DataQualityIssue, NormalisedRow } from '../types/icr';
import type { HealthDistribution, PortfolioSummary, RecommendationSummary } from '../types/report';
const CATS: Array<keyof HealthDistribution>=['Critical','Watch','Stable','Strong'];
export function buildHealthDistribution(rows: readonly NormalisedRow[]): HealthDistribution { return rows.reduce<HealthDistribution>((acc,r)=>({...acc,[healthCategory(r.health)]:acc[healthCategory(r.health)]+1}),{Critical:0,Watch:0,Stable:0,Strong:0}); }
export function buildRecommendationSummary(rows: readonly NormalisedRow[]): RecommendationSummary { const themes=new Map<string,number>(); let actionable=0; rows.forEach((r)=>{ if(isActionableRecommendation(r.recommendation)) actionable+=1; const label=r.recommendation || 'Missing recommendation'; themes.set(label,(themes.get(label)??0)+1); }); return {total:rows.length,actionable,informational:rows.length-actionable,themes:[...themes.entries()].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label)).slice(0,8)}; }
export function buildPortfolioSummary(rows: readonly NormalisedRow[], issues: readonly DataQualityIssue[]=[]): PortfolioSummary { const accountCount=new Set(rows.map((r)=>r._clientKey)).size; const healthValues=rows.map((r)=>r.health).filter(Number.isFinite); const avg=healthValues.length?Math.round(healthValues.reduce((s,v)=>s+v,0)/healthValues.length):null; const covered=rows.filter((r)=>Boolean(r.owner)).length; return {accountCount,snapshotCount:rows.length,averageHealth:avg,accountsNeedingAction:rows.filter((r)=>healthCategory(r.health)==='Critical'||healthCategory(r.health)==='Watch'||isActionableRecommendation(r.recommendation)).length,unresolvedRecommendationCount:rows.filter((r)=>isActionableRecommendation(r.recommendation)).length,ownerCoverage:{covered,total:rows.length,percent:rows.length?Math.round((covered/rows.length)*100):null},dataQualityIssueCount:issues.length}; }
export function finiteDistribution(dist: HealthDistribution): boolean { return CATS.every((c)=>Number.isFinite(dist[c])); }
