import { FIELD_DEFS, REQUIRED_FIELD_KEYS } from '../constants/fields';
import { matchHeaders } from './headerMatching';
import { isMissing, normaliseHeader, safeString } from './normaliseHeader';
import { emptyRowIssue, mappingIssues, requiredFieldIssues } from './dataQuality';
import { normaliseRows } from './normaliseRow';
import { scoreWorksheet } from './worksheetScoring';
import type { CanonicalFieldKey, RawRow } from '../types/icr';
import type { HeaderMapping, MappingCandidate } from '../types/mapping';
import type { BrowserWorkbook, ColumnMappingState, ParseResultSummary, SourceHeader, WorkbookSheetData, WorksheetCandidate } from '../types/upload';

const EXAMPLE_LIMIT = 3; const EXAMPLE_LENGTH = 42;
const truncate=(value: unknown) => { const s=safeString(value); return s.length>EXAMPLE_LENGTH?`${s.slice(0,EXAMPLE_LENGTH-1)}…`:s; };
export function findHeaderRowIndex(rows: readonly (readonly unknown[])[]): number | null { const i=rows.findIndex((row)=>row.some((cell)=>!isMissing(cell))); return i>=0?i:null; }
export function extractSourceHeaders(rows: readonly (readonly unknown[])[], headerRowIndex: number | null): SourceHeader[] { if (headerRowIndex===null) return []; const labels=[...(rows[headerRowIndex]??[])]; const mapping=matchHeaders(labels); return labels.map((label,columnIndex)=>{ const text=safeString(label) || `Column ${columnIndex+1}`; const examples:string[]=[]; for (let r=headerRowIndex+1; r<rows.length && examples.length<EXAMPLE_LIMIT; r+=1) { const sample=truncate(rows[r]?.[columnIndex]); if (sample) examples.push(sample); } return {columnIndex,label:text,normalisedLabel:normaliseHeader(text),examples,candidate:mapping[text]}; }); }
export function buildWorksheetCandidates(workbook: BrowserWorkbook): WorksheetCandidate[] { return workbook.sheets.map((sheet)=>buildWorksheetCandidate(sheet)).sort((a,b)=>b.score.score-a.score.score || a.index-b.index || a.name.localeCompare(b.name)); }
export function buildWorksheetCandidate(sheet: WorkbookSheetData): WorksheetCandidate { const headerRowIndex=findHeaderRowIndex(sheet.rows); const headers=extractSourceHeaders(sheet.rows,headerRowIndex); const score=scoreWorksheet({name:sheet.name,index:sheet.index,headers:headers.map((h)=>h.label),rowCount:sheet.rowCount,nonEmptyRowCount:sheet.nonEmptyRowCount}); return {name:sheet.name,index:sheet.index,rowCount:sheet.rowCount,nonEmptyRowCount:sheet.nonEmptyRowCount,headerRowIndex,headers,score,valid:score.valid,rows:sheet.rows.map((r)=>[...r])}; }
export function initialColumnMapping(candidate: WorksheetCandidate): ColumnMappingState { const out:ColumnMappingState={}; candidate.headers.forEach((h)=>{ if (h.candidate?.key && h.candidate.status!=='ambiguous' && h.candidate.status!=='duplicate') out[h.candidate.key]=h.label; }); return out; }
export function mappingStateToHeaderMapping(candidate: WorksheetCandidate, state: ColumnMappingState): HeaderMapping { const byHeader=new Map(candidate.headers.map((h)=>[h.label,h.candidate])); const out:Record<string,MappingCandidate>={}; candidate.headers.forEach((h)=>{ out[h.label]={sourceHeader:h.label,key:'',score:0,status:'ignore',alternatives:h.candidate?.alternatives}; }); const seen=new Set<CanonicalFieldKey>(); FIELD_DEFS.forEach((field)=>{ const header=state[field.key]; if (!header) return; const suggested=byHeader.get(header); const status=seen.has(field.key)?'duplicate':suggested?.status==='review'?'review':'auto'; out[header]={sourceHeader:header,key:field.key,score:suggested?.score??1,status,alternatives:suggested?.alternatives}; seen.add(field.key); }); return out; }
export function validateColumnMapping(candidate: WorksheetCandidate, state: ColumnMappingState) { const available=new Set(candidate.headers.map((h)=>h.label)); const missing=REQUIRED_FIELD_KEYS.filter((key)=>!state[key] || !available.has(state[key] as string)); const counts=new Map<string, CanonicalFieldKey[]>(); Object.entries(state).forEach(([key,header])=>{ if(header) counts.set(header,[...(counts.get(header)??[]), key as CanonicalFieldKey]); }); const duplicates=[...counts.entries()].filter(([,keys])=>keys.length>1).map(([header,keys])=>({header,keys})); return {ok:missing.length===0 && duplicates.length===0, missing, duplicates}; }
export async function parseWorksheetRows(candidate: WorksheetCandidate, state: ColumnMappingState, onProgress?: (p:{processedRows:number;totalRows:number;skippedRows:number})=>void): Promise<ParseResultSummary> { const validation=validateColumnMapping(candidate,state); if(!validation.ok) throw new Error('Column mapping is incomplete or duplicated.'); if(candidate.headerRowIndex===null) throw new Error('Selected worksheet does not contain a header row.'); const mapping=mappingStateToHeaderMapping(candidate,state); const rows=candidate.rows.slice(candidate.headerRowIndex+1); const sourceRows:RawRow[]=[]; const issues=[...mappingIssues(mapping),...requiredFieldIssues(mapping)]; let skippedRows=0; for (let i=0;i<rows.length;i+=1) { const raw:Record<string,unknown>={}; candidate.headers.forEach((h)=>{ raw[h.label]=rows[i]?.[h.columnIndex] ?? null; }); const empty=emptyRowIssue(raw, candidate.headerRowIndex+i+2); if (empty) { skippedRows+=1; issues.push(empty); } else sourceRows.push(Object.freeze({...raw})); if ((i+1)%100===0) { onProgress?.({processedRows:i+1,totalRows:rows.length,skippedRows}); await Promise.resolve(); } } const normalised=normaliseRows(sourceRows,mapping); onProgress?.({processedRows:rows.length,totalRows:rows.length,skippedRows}); return {rows:normalised.rows,issues:[...issues,...normalised.issues],skippedRows,mappedColumnCount:Object.values(state).filter(Boolean).length,mapping,sourceRows}; }
