import { useEffect, useMemo, useState } from 'react';
import { History, ImageDown, Sparkles } from 'lucide-react';

const QR_EDITOR_STORAGE_KEY = 'zapora_qr_editor_link';
const QR_EDITOR_RECENTS_KEY = 'zapora_qr_editor_recent_designs';
type PanelTab = 'content'|'templates'|'style'|'recent';
type OutputStyle = 'plain'|'whatsappCard'|'posterCard';
type ExportSizeId='squarePost'|'portraitPost'|'story'|'poster'|'visitingCard';
// ...keep concise types
const exportSizes={squarePost:{label:'Square Post',ratio:'1:1',w:1200,h:1200},portraitPost:{label:'Portrait Post',ratio:'4:5',w:1080,h:1350},story:{label:'Story',ratio:'9:16',w:1080,h:1920},poster:{label:'Poster',ratio:'7:10',w:1400,h:2000},visitingCard:{label:'Visiting Card',ratio:'7:4',w:1400,h:800}} as const;
const messageTemplates={general:'Hi, I’d like to know more about your services.',support:'Hi, I need help regarding your service/product.',booking:'Hi, I’d like to book an appointment.',pricing:'Hi, I’d like to get pricing details.',order:'Hi, I’d like to place an order.',event:'Hi, I want to register for your event.',collab:'Hi, I’d like to discuss a possible collaboration.',freelance:'Hi, I’d like to discuss a project with you.'} as const;
const tones={professional:['Connect with us on WhatsApp','Scan to start a professional conversation'],friendly:['Let’s chat on WhatsApp','We’re one message away'],sales:['Message us for offers and pricing','Get a quick quote today'],support:['Need help? Reach us on WhatsApp','Our support team is ready'],minimal:['Chat on WhatsApp','Scan to message']} as const;
const posterPresets={cleanBusiness:'bg-white border-gray-200',softModern:'bg-slate-50 border-slate-200',boldPromo:'bg-gray-900 border-gray-800',minimalContact:'bg-white border-gray-100',eventStyle:'bg-indigo-50 border-indigo-200'} as const;

export default function QrCodeEditorPage(){
const [tab,setTab]=useState<PanelTab>('content'); const [targetLink,setTargetLink]=useState(''); const [msg,setMsg]=useState(messageTemplates.general); const [title,setTitle]=useState(tones.professional[0]); const [subtitle,setSubtitle]=useState(tones.professional[1]); const [style,setStyle]=useState<OutputStyle>('whatsappCard'); const [size,setSize]=useState<ExportSizeId>('squarePost'); const [poster,setPoster]=useState<keyof typeof posterPresets>('cleanBusiness'); const [color,setColor]=useState('#000000'); const [grad,setGrad]=useState('linear-gradient(135deg, #7b61ff, #b16cea, #5ce1e6)'); const [useGradient,setUseGradient]=useState(false); const [recent,setRecent]=useState<any[]>([]); const [status,setStatus]=useState('');
useEffect(()=>{const s=localStorage.getItem(QR_EDITOR_STORAGE_KEY); if(s) setTargetLink(s); const r=localStorage.getItem(QR_EDITOR_RECENTS_KEY); if(r) setRecent(JSON.parse(r));},[]);
useEffect(()=>localStorage.setItem(QR_EDITOR_RECENTS_KEY,JSON.stringify(recent.slice(0,5))),[recent]);
const valid=useMemo(()=>{try{return !!targetLink.trim()&&Boolean(new URL(targetLink));}catch{return false;}},[targetLink]);
const finalLink=useMemo(()=>{if(!valid) return ''; const u=new URL(targetLink); if((u.hostname.includes('wa.me')||u.hostname.includes('whatsapp'))&&msg.trim()) u.searchParams.set('text',msg.trim()); return u.toString();},[valid,targetLink,msg]);
const qr=`${finalLink?`https://api.qrserver.com/v1/create-qr-code/?size=640x640&color=${color.replace('#','')}&bgcolor=ffffff&data=${encodeURIComponent(finalLink)}`:''}`;
const cfg=exportSizes[size];
const renderCanvas=async()=>{const c=document.createElement('canvas'); c.width=cfg.w;c.height=cfg.h; const x=c.getContext('2d'); if(!x) return null; x.fillStyle='#f8fafc'; x.fillRect(0,0,c.width,c.height); const pad=Math.round(Math.min(c.width,c.height)*0.06); x.fillStyle='#fff'; x.strokeStyle='#e5e7eb'; x.lineWidth=2; x.beginPath(); x.roundRect(pad,pad,c.width-pad*2,c.height-pad*2,32); x.fill(); x.stroke(); if(style!=='plain'){const g=x.createLinearGradient(pad,pad,c.width-pad,pad+120); g.addColorStop(0,useGradient?'#7b61ff':color); g.addColorStop(1,useGradient?'#5ce1e6':'#111827'); x.fillStyle=g; x.beginPath(); x.roundRect(pad,pad,c.width-pad*2,Math.round((c.height-pad*2)*0.14),[32,32,18,18]); x.fill();}
const img=await new Promise<HTMLImageElement>((res,rej)=>{const i=new Image(); i.crossOrigin='anonymous'; i.src=qr; i.onload=()=>res(i); i.onerror=()=>rej();}); const qs=Math.round(Math.min(c.width,c.height)*(style==='posterCard'?0.5:0.42)); const qx=(c.width-qs)/2; const qy=style==='plain'?pad+Math.round((c.height-pad*2)*0.24):pad+Math.round((c.height-pad*2)*0.32); x.fillStyle='#fff';x.beginPath();x.roundRect(qx-20,qy-20,qs+40,qs+40,22);x.fill();x.drawImage(img,qx,qy,qs,qs); if(style!=='plain'){x.textAlign='center'; x.fillStyle=poster==='boldPromo'?'#f8fafc':'#0f172a'; x.font=`700 ${Math.round(c.height*0.04)}px Inter`; x.fillText(title,c.width/2,pad+Math.round((c.height-pad*2)*0.18)); x.fillStyle=poster==='boldPromo'?'#cbd5e1':'#475569'; x.font=`400 ${Math.round(c.height*0.022)}px Inter`; x.fillText(subtitle,c.width/2,pad+Math.round((c.height-pad*2)*0.23));}
return c;};
const exportPNG=async()=>{if(!qr)return; const c=await renderCanvas(); if(!c)return; const a=document.createElement('a'); a.download=`zapora-${style}-${size}.png`; a.href=c.toDataURL('image/png'); a.click(); setRecent(p=>[{id:Date.now(),link:targetLink,title,subtitle,style,size,poster},...p].slice(0,5)); setStatus('PNG downloaded');};
const exportSVG=()=>{if(!qr)return; const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='${cfg.w}' height='${cfg.h}'><rect width='100%' height='100%' fill='#f8fafc'/><rect x='60' y='60' rx='32' width='${cfg.w-120}' height='${cfg.h-120}' fill='white' stroke='#e5e7eb'/><text x='50%' y='150' text-anchor='middle' font-size='44' font-family='Arial' fill='#0f172a'>${title.replace(/&/g,'and')}</text><image href='${qr}' x='${(cfg.w-640)/2}' y='${(cfg.h-640)/2}' width='640' height='640'/></svg>`; const blob=new Blob([svg],{type:'image/svg+xml'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`zapora-${style}-${size}.svg`; a.click(); URL.revokeObjectURL(a.href); setStatus('SVG exported');};
const exportPDF=async()=>{const c=await renderCanvas(); if(!c)return; const w=window.open('','_blank'); if(!w)return; w.document.write(`<img src='${c.toDataURL('image/png')}' style='width:100%;max-width:900px;display:block;margin:auto'/>`); w.document.close(); w.focus(); w.print(); setStatus('PDF print dialog opened');};

return <main className='bg-gradient-to-b from-white via-green-50/30 to-white py-14'><div className='mx-auto max-w-7xl px-4'><header className='mb-8 text-center'><h1 className='text-3xl font-bold text-gray-950 sm:text-4xl'>Zapora QR Design Studio</h1><p className='mt-2 text-gray-600'>Premium WhatsApp QR assets with live preview and multi-format export.</p></header><section className='grid gap-6 lg:grid-cols-[1.1fr_0.9fr]'><div className='rounded-3xl border border-gray-200 bg-white p-4 sm:p-6'><div className='mb-4 flex flex-wrap gap-2'>{(['content','templates','style','recent'] as PanelTab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full px-4 py-2 text-sm font-medium ${tab===t?'bg-gray-900 text-white':'bg-gray-100 text-gray-700'}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
{tab==='content'&&<div className='space-y-4'><input value={targetLink} onChange={e=>setTargetLink(e.target.value)} className='w-full rounded-xl border border-gray-300 px-4 py-3' placeholder='Paste your WhatsApp link or URL'/><textarea value={msg} onChange={e=>setMsg(e.target.value)} className='w-full rounded-xl border border-gray-300 px-4 py-3' rows={3}/></div>}
{tab==='templates'&&<div className='space-y-4'><div className='grid grid-cols-2 gap-2'>{Object.entries(messageTemplates).map(([k,v])=><button key={k} onClick={()=>setMsg(v)} className='rounded-xl border border-gray-300 bg-gray-50 px-3 py-2 text-left text-sm'>{k}</button>)}</div><div className='grid grid-cols-2 gap-2 sm:grid-cols-5'>{Object.entries(tones).map(([k,v])=><button key={k} onClick={()=>{setTitle(v[0]);setSubtitle(v[1]);}} className='rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm'>{k}</button>)}</div></div>}
{tab==='style'&&<div className='space-y-4'><div className='grid grid-cols-3 gap-2'>{(['plain','whatsappCard','posterCard'] as OutputStyle[]).map(s=><button key={s} onClick={()=>setStyle(s)} className={`rounded-xl border px-3 py-2 text-sm ${style===s?'border-gray-900 bg-gray-900 text-white':'border-gray-300'}`}>{s}</button>)}</div><input value={title} onChange={e=>setTitle(e.target.value)} className='w-full rounded-xl border border-gray-300 px-3 py-2'/><input value={subtitle} onChange={e=>setSubtitle(e.target.value)} className='w-full rounded-xl border border-gray-300 px-3 py-2'/><div className='flex items-center gap-3'><input type='color' value={color} onChange={e=>setColor(e.target.value)}/><button onClick={()=>setUseGradient(v=>!v)} className='rounded-xl border border-gray-300 px-3 py-2 text-sm'>{useGradient?'Gradient On':'Gradient Off'}</button></div>{style==='posterCard'&&<div className='grid grid-cols-2 gap-2'>{Object.keys(posterPresets).map(p=><button key={p} onClick={()=>setPoster(p as any)} className={`rounded-xl border px-2 py-2 text-xs ${poster===p?'border-gray-900 bg-gray-900 text-white':'border-gray-300'}`}>{p}</button>)}</div>}</div>}
{tab==='recent'&&<div className='space-y-2'>{recent.length===0?<p className='text-sm text-gray-500'>No recent designs yet.</p>:recent.map((r:any)=><button key={r.id} onClick={()=>{setTargetLink(r.link);setTitle(r.title);setSubtitle(r.subtitle);setStyle(r.style);setSize(r.size);setPoster(r.poster);}} className='w-full rounded-xl border border-gray-300 bg-gray-50 px-3 py-2 text-left text-xs'><p className='truncate font-medium'>{r.title}</p><p className='truncate text-gray-500'>{r.link}</p></button>)}</div>}
</div>
<div className='space-y-4 lg:sticky lg:top-6 lg:self-start'><div className='rounded-3xl border border-gray-200 bg-white p-5 shadow-inner'><h2 className='text-sm font-semibold uppercase tracking-wide text-gray-500'>Live Preview</h2>{valid&&qr?<div className='mt-4 grid min-h-[420px] place-items-center rounded-2xl border border-dashed border-gray-300 bg-white p-4'><div className={`w-full max-w-md rounded-3xl border p-4 shadow-lg ${posterPresets[poster]}`} style={{aspectRatio:`${cfg.w}/${cfg.h}`}}><div className={`${style==='plain'?'hidden':''} mb-3 rounded-2xl p-3 text-center text-white`} style={useGradient?{backgroundImage:grad}:{backgroundColor:color}}><p className='text-sm font-semibold sm:text-base'>{title}</p><p className='text-xs opacity-90'>{subtitle}</p></div><div className='mx-auto w-fit rounded-2xl border border-gray-200 bg-white p-3'><img src={qr} className='h-44 w-44 sm:h-56 sm:w-56' alt='preview'/></div></div></div>:<div className='mt-4 flex min-h-[420px] flex-col items-center justify-center rounded-2xl border border-dashed border-gray-300 bg-white text-center'><Sparkles className='mb-2 h-5 w-5 text-green-600'/><p className='font-semibold'>Start with a link</p><p className='text-sm text-gray-600'>Paste URL, tune style, and export.</p></div>}</div>
<div className='rounded-3xl border border-gray-200 bg-white p-5'><h3 className='mb-3 text-sm font-semibold uppercase tracking-wide text-gray-500'>Export</h3><div className='mb-3 grid grid-cols-2 gap-2'>{(Object.keys(exportSizes) as ExportSizeId[]).map(k=><button key={k} onClick={()=>setSize(k)} className={`rounded-xl border px-2 py-2 text-xs ${size===k?'border-gray-900 bg-gray-900 text-white':'border-gray-300 bg-gray-50'}`}>{exportSizes[k].label} <span className='text-[10px] opacity-70'>{exportSizes[k].ratio}</span></button>)}</div><div className='grid grid-cols-3 gap-2'><button onClick={exportPNG} disabled={!valid} className='rounded-xl bg-gray-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60'>PNG</button><button onClick={exportSVG} disabled={!valid} className='rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm'>SVG</button><button onClick={exportPDF} disabled={!valid} className='rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm'>PDF</button></div><p className='mt-2 text-xs text-gray-500'>{status}</p></div></div>
</section></div></main>
}

export { QR_EDITOR_STORAGE_KEY };
