import { ArrowUpRight, Globe2, Package, PanelTop, ScanLine, UsersRound } from 'lucide-react';

const uses = [
  { icon: PanelTop, title: 'Website & landing pages', text: 'Give visitors a direct route to your WhatsApp chat.', color: 'bg-emerald-100 text-emerald-700' },
  { icon: UsersRound, title: 'Social bios', text: 'Keep your profile link useful and easy to act on.', color: 'bg-cyan-100 text-cyan-700' },
  { icon: ScanLine, title: 'Posters & flyers', text: 'Turn offline attention into an instant conversation.', color: 'bg-amber-100 text-amber-700' },
  { icon: Package, title: 'Packaging & storefronts', text: 'Offer help, reorders, and support at the point of need.', color: 'bg-violet-100 text-violet-700' },
];
export default function SeoContent() { return <section className="bg-[#f8fcfa] py-14 sm:py-20"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:items-start lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Built for real touchpoints</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Put a WhatsApp conversation where people need it.</h2><p className="mt-4 text-sm leading-7 text-slate-600 sm:text-base">A WhatsApp link generator creates a direct chat link without asking people to save a number first. Zapora adds an optional first message and a QR code so the same destination works online and off.</p><a href="/qr-code-editor" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-emerald-700 transition hover:text-emerald-900 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/20">Need more QR styling? Open the editor <ArrowUpRight className="h-4 w-4" /></a></div><div className="grid gap-3 sm:grid-cols-2">{uses.map((use) => <article key={use.title} className="rounded-2xl border border-white bg-white p-5 shadow-[0_14px_28px_-28px_rgba(15,23,42,.4)]"><div className={`grid h-10 w-10 place-items-center rounded-xl ${use.color}`}><use.icon className="h-5 w-5" /></div><h3 className="mt-4 text-sm font-bold text-slate-900">{use.title}</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">{use.text}</p></article>)}</div><p className="lg:col-span-2 flex items-center gap-2 text-xs text-slate-500"><Globe2 className="h-4 w-4 text-emerald-600" />Share one clean wa.me link across your campaigns, customer support, and everyday materials.</p></div></section>; }
